### ISSUE TITLE
Missing Content?

### ISSUE THREAD

**Issue by ericcberg** [YanKlInnomme/FoundryVTT-k4lt-assets#2]
When I add the module, the only package in the compendium is the OST. I don't see where the artwork is?

**Comment by YanKlInnomme** [comment]
The resources are in the 'img', 'mp3', 'pdf', 'scenarios' folders. As explained in the description, these are raw resources intended to be used to feed other modules.

**Comment by ericcberg** [comment]
Got it, thanks!
